spring:
  application:
    name: cart-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
  info:
    component: Cart Service

logging: ##Uygulamadaki logları takip edebilmek için eklenen conf.
  level:
    ##root: debug
    ##root: off
    com.microshop: debug
    ##üstteki şekilde diyerek daha az ve daha az karışık log görebiliriz.
server:
  port: 9792

---
spring:
  config:
    activate:
      on-profile: localhost
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    config:
      uri: http://localhost:8890
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5435/cart"
    username: postgres
    password: postgres

feign:
  product-service:
    name: product-service
    url: http://localhost:9788
  user-service:
    name: user-service
    url: http://localhost:9789

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: stage
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:1001/cart"
    username: postgres
    password: postgres
    #is bilgisayarında şifre postgres. evdeki bilgisayarda postgre.

feign:
  product-service:
    name: product-service
    url: http://zuul-edge-server:1002
  user-service:
    name: user-service
    url: http://zuul-edge-server:1002


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://eureka-server:1003/eureka/