spring:
  application:
    name: cart-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
  info:
    component: Cart Service

logging: ##Uygulamadaki logları takip edebilmek için eklenen conf.
  level:
    ##root: debug
    ##root: off
    com.microshop: debug
    ##üstteki şekilde diyerek daha az ve daha az karışık log görebiliriz.
server:
  port: 9792

---
spring:
  config:
    activate:
      on-profile: localhost

feign:
  product-service:
    name: product-service
    url: http://localhost:9788
  user-service:
    name: user-service
    url: http://localhost:9789

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: stage

feign:
  product-service:
    name: product-service
    url: http://zuul-edge-server:8762
  user-service:
    name: user-service
    url: http://zuul-edge-server:8762


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/